import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import Lights from './Lights'

const withPhysics = (Component) => (props) => {
  const ref = useRef()
  return (
    <RigidBody ref={ref} {...props} type="fixed">
      <Component {...props} />
    </RigidBody>
  )
}

const WorldLevelTwo = (props) => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelTwo/LevelTwo.glb'
  )

  return (
    <>
      <Lights />
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor.geometry}
          material={materials['Material.001']}
        />
        <group position={[0, 0, -9.224]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.AncientRuins_Sword_M_AncientRuins_Props_0.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.AncientRuins_Sword_M_AncientRuins_Props_0001.geometry
            }
            material={materials['Material.004']}
          />
        </group>
        <group position={[0, 0, 35.617]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.AncientRuins_Sword_M_AncientRuins_Props_0002.geometry
            }
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.AncientRuins_Sword_M_AncientRuins_Props_0003.geometry
            }
            material={materials['Material.004']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallCemetary1.geometry}
          material={materials.None}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallCemetary2.geometry}
          material={materials.None}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VerticalFence2.geometry}
          material={materials.ma}
        />
        <group position={[0, 0, -21.832]} scale={[1, 1.2, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FranksC352SC130kDC32270kM2064k_0.geometry}
            material={materials['Franks.C352.SC130k.DC32270k.M2064k']}
            position={[0.564, 0, -8.504]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_L_1.geometry}
          material={materials.DarkWood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_L_2.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_L_3.geometry}
          material={materials['Wood.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_L_4.geometry}
          material={materials.Metal_Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_R_1.geometry}
          material={materials.DarkWood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_R_2.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_R_3.geometry}
          material={materials['Wood.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_RoundArch_R_4.geometry}
          material={materials.Metal_Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0001.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0002.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1002.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0001.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0003.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1003.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0004.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1004.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface53_lambert2_0.geometry}
          material={materials['lambert2.001']}
          position={[0, 0, -16.881]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0010.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0011.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0012.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0013.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0005.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0009.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0014.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0005.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub005_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub006_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub007_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub008_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub009_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub004_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub003_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub002_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub001_0008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0015.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laub_0016.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm005_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm006_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm007_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm008_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm009_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm004_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm003_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm002_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm001_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stamm_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne008_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne004_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne005_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne006_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_0006.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne007_1006.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne003_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_0007.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne001_1007.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne002_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_0008.geometry}
          material={materials.Holzbraun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tanne_1008.geometry}
          material={materials.Tannengrn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.crypt.geometry}
          material={materials.HalloweenBits}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.crypt001.geometry}
          material={materials.HalloweenBits}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial006.geometry}
          material={materials.ma}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007.geometry}
          material={materials.ma}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial034.geometry}
          material={materials.ma}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material001_0.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Material002_0.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material002_0.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material001_0.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material_0.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material002_0.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material002_0.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material002_0.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Material002_0001.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material002_0001.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material001_0001.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material_0001.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material002_0001.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material002_0001.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material002_0001.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Material002_0002.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material002_0002.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material001_0002.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material_0002.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material002_0002.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material002_0002.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material002_0002.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_Material002_0003.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_Material002_0003.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material001_0003.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material_0003.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Material002_0003.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Material002_0003.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material002_0003.geometry}
          material={materials['Material.006']}
        />
      </group>
    </>
  )
}

useGLTF.preload('/Cemetery.glb')

const WorldLevelTwoWithPhysics = withPhysics(WorldLevelTwo)

export default WorldLevelTwoWithPhysics
