import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

const withPhysics = (Component, ComponentFixed) => (props) => {
  return (
    <>
      <RigidBody type="fixed">
        <Component />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <ComponentFixed />
      </RigidBody>
    </>
  )
}

export const WorldLevelFourTrimesh = (props) => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelFour/LevelFour.glb'
  )
  return (
    <>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle001.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance001_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance001_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor005.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor005.geometry}
        material={materials['grey.001']}
      />
    </>
  )
}

const WorldLevelFour = (props) => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelFour/LevelFour.glb'
  )
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor004.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor001.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor003.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof001.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof002.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof003.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof004.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof005.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cliff.geometry}
        material={materials.Cliff}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Key.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stones.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shield.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofMain.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_Wood_Broken001.geometry}
        material={materials.Atlas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_Wood_Broken002.geometry}
        material={materials.Atlas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_Wood_Broken003.geometry}
        material={materials.Atlas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_Wood_Broken004.geometry}
        material={materials.Atlas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_Wood_Broken005.geometry}
        material={materials.Atlas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_Wood_Broken006.geometry}
        material={materials.Atlas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow001.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow002.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow003.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow004.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow005.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow006.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow007.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow008.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow009.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow010.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow011.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow012.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow013.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow014.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow015.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow016.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow017.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow018.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow019.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow020.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow021.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow022.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow023.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow024.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow025.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow026.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow027.geometry}
        material={materials['Material.002']}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy003.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy004.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy005.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy006.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy007.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy008.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy009.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy010.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy011.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy012.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy013.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy014.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy015.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy016.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy017.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy018.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy019.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy020.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy027.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy028.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy029.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy030.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy031.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy032.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy033.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy034.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy035.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy036.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy037.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy038.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy039.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy040.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy041.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy042.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy043.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy044.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush001.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush002.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush003.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush004.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush005.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint001.geometry}
        material={materials['Stone.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint002.geometry}
        material={materials['Stone.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint.geometry}
        material={materials['Stone.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint003.geometry}
        material={materials['Stone.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench001.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench002.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench003.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench004.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench005.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench006.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench007.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bench008.geometry}
        material={materials.DarkWood}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LionStatue_1.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LionStatue_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LionStatue_3.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_3.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_4.geometry}
        material={materials.Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_3.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_4.geometry}
        material={materials.Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_1.geometry}
        material={materials['Wood.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_2.geometry}
        material={materials['DarkWood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_3.geometry}
        material={materials['Metal.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_4.geometry}
        material={materials['DarkMetal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sign_1.geometry}
        material={materials.mat20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sign_2.geometry}
        material={materials.mat19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue002_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue002_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue002_3.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue002_4.geometry}
        material={materials.Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue003_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue003_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue003_3.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue003_4.geometry}
        material={materials.Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_0.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_0_1.geometry}
        material={materials['Material.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_0_2.geometry}
        material={materials['Material.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_0_3.geometry}
        material={materials['Material.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs_1.geometry}
        material={materials.DarkMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs_2.geometry}
        material={materials.Fire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs001_1.geometry}
        material={materials.DarkMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs001_2.geometry}
        material={materials.Fire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel006_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel006_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel006_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel013_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel013_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel013_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel015_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel015_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel015_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel038.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel038_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel038_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel039.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel039_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel039_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel040.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel040_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel040_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel041.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel041_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel041_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel042.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel042_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel042_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel043.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel043_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel043_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel044.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel044_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel044_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel045.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel045_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel045_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel046.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel046_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel046_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel047.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel047_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel047_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel048.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel048_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel048_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel049.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel049_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel049_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel050.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel050_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel050_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel051.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel051_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel051_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel052.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel052_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel052_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel053.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel053_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel053_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel054.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel054_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel054_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel055.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel055_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel055_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel056.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel056_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel056_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel057.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel057_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel057_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel058.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel058_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel058_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel059.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel059_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel059_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel060.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel060_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel060_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel061.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel061_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel061_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel062.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel062_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel062_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel063.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel063_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel063_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel064.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel064_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel064_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel065.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel065_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel065_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel066.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel066_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel066_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel067.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel067_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel067_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel068.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel068_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel068_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel069.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel069_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel069_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel070.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel070_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel070_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel071.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel071_1.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel071_2.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree001_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree001_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree002_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree002_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree003_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree003_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree004_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree004_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree005_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree005_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree006_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree006_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree007_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree007_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree008_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree008_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree009_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree009_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree010_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree010_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree011_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree011_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree012_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree012_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree013_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree013_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree014_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree014_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree015_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree015_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree016_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree016_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree017_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree017_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree018_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree018_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree019_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree019_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree020_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree020_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree021_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree021_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree022_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree022_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree023_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree023_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box004_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box004_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box032.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box032_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box033.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box033_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box034.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box034_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box035.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box035_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box036.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box036_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box037.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box037_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box038.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box038_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box039.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box039_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box040.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box040_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box041.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box041_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box042.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box042_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box043.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box043_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box044.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box044_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box045.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box045_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box046.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box046_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box047.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box047_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box048.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box048_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box049.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box049_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box050.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box050_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box051.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box051_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box052.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box052_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box053.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box053_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box054.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box054_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box055.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box055_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box056.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box056_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box057.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box057_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box058.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box058_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box059.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box059_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box060.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box060_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box061.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box061_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box062.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box062_1.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond001_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond001_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond001_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond002_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond002_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond002_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond003_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond003_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond003_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond004_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond004_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond004_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond005_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond005_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond005_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond006_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond006_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond006_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond007_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond007_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond007_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond008_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond008_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond008_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond009_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond009_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond009_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond010_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond010_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond010_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond011_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond011_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond011_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond012_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond012_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond012_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond013_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond013_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond013_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond014_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond014_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond014_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond015_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond015_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond015_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond016_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond016_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond016_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond017_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond017_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond017_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond018_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond018_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond018_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond019_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond019_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond019_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond020_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond020_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond020_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_2.geometry}
        material={materials.Stone_Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_3.geometry}
        material={materials['Wood.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_4.geometry}
        material={materials['Main.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_2.geometry}
        material={materials.Stone_Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_3.geometry}
        material={materials['Wood.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_4.geometry}
        material={materials['Main.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner001_1.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner001_2.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner001_3.geometry}
        material={materials.Main}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner002_1.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner002_2.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner002_3.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner003_1.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner003_2.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner003_3.geometry}
        material={materials.mat19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner004_1.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner004_2.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner004_3.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006_1.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006_2.geometry}
        material={materials.Main}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner005_1.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner005_2.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner005_3.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner006_1.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner006_2.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner006_3.geometry}
        material={materials.mat19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner_1.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner_2.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Banner_3.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_1.geometry}
        material={materials['Wood.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_2.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_3.geometry}
        material={materials['DarkMetal.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table001_1.geometry}
        material={materials['Wood.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table001_2.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table001_3.geometry}
        material={materials['DarkMetal.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table002_1.geometry}
        material={materials['Wood.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table002_2.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table002_3.geometry}
        material={materials['DarkMetal.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table003_1.geometry}
        material={materials['Wood.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table003_2.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table003_3.geometry}
        material={materials['DarkMetal.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table004_1.geometry}
        material={materials['Wood.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table004_2.geometry}
        material={materials.DarkWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table004_3.geometry}
        material={materials['DarkMetal.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chandelier_1.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chandelier_2.geometry}
        material={materials.Cliff}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chandelier_3.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier004_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier004_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier004_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier004_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier004_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier004_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier003_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier003_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier003_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier003_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier003_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier003_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier001_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier001_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier001_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier001_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier001_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier001_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier002_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier002_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier002_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier002_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier002_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier002_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier005_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier005_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier005_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier005_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier005_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier005_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier006_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier006_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier006_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier006_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier006_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier006_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier007_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier007_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier007_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier007_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier007_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier007_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier_1.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier_2.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier_3.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier_4.geometry}
        material={materials['Metal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brazier_6.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron001_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron001_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron002_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron002_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron003_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron003_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron004_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron004_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron005_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron005_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron006_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron006_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron007_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron007_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron008_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron008_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron_1.geometry}
        material={materials.Green_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cauldron_2.geometry}
        material={materials.Black_Cauldron}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library002_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library002_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library002_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library002_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library002_5.geometry}
        material={materials['mat20.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library001_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library001_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library001_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library001_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library001_5.geometry}
        material={materials['mat20.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library_5.geometry}
        material={materials['mat20.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library003_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library003_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library003_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library003_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library003_5.geometry}
        material={materials['mat20.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library004_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library004_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library004_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library004_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library004_5.geometry}
        material={materials['mat20.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library005_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library005_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library005_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library005_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library005_5.geometry}
        material={materials['mat20.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library006_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library006_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library006_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library006_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library006_5.geometry}
        material={materials['mat20.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library007_1.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library007_2.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library007_3.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library007_4.geometry}
        material={materials['mat9.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Library007_5.geometry}
        material={materials['mat20.001']}
      />
    </group>
  )
}

useGLTF.preload('/LevelFour.glb')

const WorldLevelFourWithPhysisc = withPhysics(
  WorldLevelFour,
  WorldLevelFourTrimesh
)

export default WorldLevelFourWithPhysisc
