import React from 'react'
import { useGLTF } from '@react-three/drei'

const WorldLevelFour = (props) => {
  const { nodes, materials } = useGLTF(
    '/public/assets/models/worldLevelFour/LevelFour.glb'
  )
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor004.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor001.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor003.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor005.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge.geometry}
        material={materials['grey.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cliff.geometry}
        material={materials.Cliff}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle002.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle003.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle004.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle005.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle006.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle007.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cliff001.geometry}
        material={materials.Cliff}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow001.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow002.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow003.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow004.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow005.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow006.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow007.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow008.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow009.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow010.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow011.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow012.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow013.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow014.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow015.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow016.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow017.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow018.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow019.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow020.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow021.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow022.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow023.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow024.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow025.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow026.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LightWindow027.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Castle001.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy001.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy002.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy003.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy004.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy005.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy006.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy007.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy008.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy009.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy010.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ivy011.geometry}
        material={materials.blinn1SG}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush001.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush002.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush003.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush004.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush005.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group821822121.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Key4.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Statue_Stag.geometry}
        material={materials['Stone.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Statue_Stag001.geometry}
        material={materials['Stone.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Statue_Stag002.geometry}
        material={materials['Stone.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance001_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Entrance001_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LionStatue_1.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LionStatue_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LionStatue_3.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_3.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue_4.geometry}
        material={materials.Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_2.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_3.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WarriorStatue001_4.geometry}
        material={materials.Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs_1.geometry}
        material={materials.DarkMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs_2.geometry}
        material={materials.Fire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs001_1.geometry}
        material={materials.DarkMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torchs001_2.geometry}
        material={materials.Fire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel001_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel001_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel001_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel002_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel002_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel002_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel003_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel003_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel003_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel004_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel004_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel004_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel005_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel005_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel005_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel006_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel006_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel006_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel007_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel007_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel007_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel008_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel008_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel008_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel009_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel009_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel009_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel010_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel010_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel010_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel011_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel011_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel011_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel012_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel012_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel012_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel013_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel013_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel013_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel014_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel014_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel014_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel015_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel015_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel015_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel016_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel016_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel016_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel017_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel017_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel017_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel018_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel018_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel018_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel019_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel019_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel019_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel020_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel020_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel020_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel021_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel021_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel021_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel022_1.geometry}
        material={materials['Wood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel022_2.geometry}
        material={materials['Stone.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel022_3.geometry}
        material={materials['DarkWood.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree001_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree001_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree002_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree002_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree003_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree003_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree004_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree004_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree005_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree005_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree006_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree006_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree007_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree007_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree008_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree008_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree009_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree009_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree010_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree010_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree011_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree011_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree012_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree012_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree013_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree013_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree014_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree014_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree015_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree015_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree016_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree016_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree017_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree017_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree018_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree018_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree019_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree019_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree020_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree020_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree021_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree021_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree022_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree022_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree023_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree023_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1.geometry}
        material={materials['Wood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box002_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box002_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box003_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box003_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box004_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box004_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box001_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box001_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box005_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box005_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box006_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box006_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box007_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box007_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box008_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box008_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box009_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box009_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box010_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box010_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box011_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box011_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box012_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box012_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box013_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box013_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box014_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box014_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box015_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box015_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box016_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box016_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box017_1.geometry}
        material={materials['DarkWood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box017_2.geometry}
        material={materials['Wood.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_2.geometry}
        material={materials.Stone_Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_3.geometry}
        material={materials['Wood.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain_4.geometry}
        material={materials['Main.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_2.geometry}
        material={materials.Stone_Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_3.geometry}
        material={materials['Wood.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallMain002_4.geometry}
        material={materials['Main.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond001_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond001_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond001_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond002_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond002_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond002_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond003_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond003_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond003_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond004_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond004_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond004_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond005_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond005_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond005_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond006_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond006_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond006_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond007_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond007_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond007_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond008_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond008_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond008_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond009_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond009_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond009_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond010_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond010_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond010_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond011_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond011_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond011_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond012_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond012_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond012_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond013_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond013_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond013_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond014_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond014_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond014_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond015_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond015_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond015_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond016_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond016_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond016_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond017_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond017_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond017_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond018_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond018_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond018_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond019_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond019_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond019_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond020_1.geometry}
        material={materials.Dark_Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond020_2.geometry}
        material={materials['Stone_Light.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSecond020_3.geometry}
        material={materials['Wood.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_1.geometry}
        material={materials['Wood.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_2.geometry}
        material={materials['DarkWood.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_3.geometry}
        material={materials['Metal.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_4.geometry}
        material={materials['DarkMetal.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model_1.geometry}
        material={materials.mat20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model_2.geometry}
        material={materials.mat19}
      />
    </group>
  )
}

useGLTF.preload('/LevelFour.glb')

export default WorldLevelFour
