import React from 'react'
import { useGLTF } from '@react-three/drei'
import { CuboidCollider, RigidBody } from '@react-three/rapier'

const BackPacks = () => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelOne/LevelOne.glb'
  )

  return (
    <RigidBody type="fixed" colliders={false} /*args={[10, 10, 10]}*/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_20.geometry}
        material={materials.mat0}
      />
      <CuboidCollider args={[0.7, 8, 0.5]} position={[5, 1, -79]} />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_20.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_21.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_20.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_21.geometry}
        material={materials.mat3}
      />
      <CuboidCollider args={[1.4, 8, 0.8]} position={[4, 1, -70.8]} />
    </RigidBody>
  )
}

export default BackPacks
