import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const withRotation = (Component) => (props) => {
  const ref = useRef()
  const refWorld = useRef()
  useFrame(() => {
    ref.current.rotation.y += 0.005
  })
  return (
    <mesh ref={ref}>
      <Component ref={refWorld} {...props} />
    </mesh>
  )
}

export function WorldLevelOne(props) {
  const { nodes, materials } = useGLTF('/assets/preview/LevelOnePreview.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cliff.geometry}
        material={materials.Cliff}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofMain.geometry}
        material={materials['mat20.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofSide.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofSide001.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train001.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCentral_1.geometry}
        material={materials['mat17.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCentral_2.geometry}
        material={materials['mat22.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner_1.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner_2.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner001_1.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner001_2.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar001_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar001_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar002_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar002_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar003_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar003_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar004_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar004_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar005_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar005_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide_1.geometry}
        material={materials['Red.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide_2.geometry}
        material={materials['Red_Dark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide_3.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide_1.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide_2.geometry}
        material={materials['mat22.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain_1.geometry}
        material={materials['mat19.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain_2.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide004_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide004_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide003_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide003_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide002_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide002_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide001_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide001_2.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide005_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide005_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide006_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide006_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide007_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide007_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide008_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide008_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide009_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide009_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide010_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide010_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide011_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide011_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide012_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide012_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide013_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide013_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide014_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide014_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide015_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide015_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain001_1.geometry}
        material={materials['mat19.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain001_2.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide001_1.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide001_2.geometry}
        material={materials['mat22.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide016_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide016_2.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide017_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide017_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide018_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide018_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide019_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide019_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide001_1.geometry}
        material={materials['Red.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide001_2.geometry}
        material={materials['Red_Dark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide001_3.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide020_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide020_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide021_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide021_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide023_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide023_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide024_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide024_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide025_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide025_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide026_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide026_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide027_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide027_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide028_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide028_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide029_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide029_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide030.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide030_1.geometry}
        material={materials['Material.001']}
      />
    </group>
  )
}

useGLTF.preload('/LevelOnePreview.glb')

export const WorldLevelOneWithRotation = withRotation(WorldLevelOne)
