import React, { useRef, createRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, interactionGroups } from '@react-three/rapier'

const withPhysics =
  (Component, ComponentTrimesh, ComponentDynamic) => (props) => {
    return (
      <>
        <RigidBody type="fixed" collisionGroups={interactionGroups(0)}>
          <Limits />
        </RigidBody>
        <RigidBody type="fixed" collisionGroups={interactionGroups(0)}>
          <Component />
        </RigidBody>
        <RigidBody type="fixed" colliders="trimesh">
          <ComponentTrimesh />
        </RigidBody>
        <ComponentDynamic />
      </>
    )
  }

const Limits = () => {
  const { nodes } = useGLTF('/assets/models/worldLevelOne/LevelOne.glb')

  const geometries = [
    nodes.Limit.geometry,
    nodes.Limit001.geometry,
    nodes.Limit002.geometry,
    nodes.Limit003.geometry,
    nodes.Limit004.geometry,
    nodes.Limit005.geometry,
    nodes.Limit006.geometry,
    nodes.Limit007.geometry,
    nodes.Limit008.geometry,
    nodes.Limit009.geometry,
  ]

  const transparentMaterial = useMemo(() => <meshPhongMaterial transparent />)

  return (
    <>
      {geometries.map((geometry, index) => (
        <mesh
          key={index}
          castShadow
          receiveShadow
          geometry={geometry}
          material={transparentMaterial}
        />
      ))}
    </>
  )
}

const BarrelsDynamic = () => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelOne/LevelOne.glb'
  )

  const arrLength = 13
  const refs = useRef([])

  if (refs.current.length !== arrLength) {
    refs.current = Array(arrLength)
      .fill()
      .map((_, i) => refs.current[i] || createRef())
  }

  const onHitBox = (i) => {
    refs.current[i].current.applyImpulse({ x: 0, y: -100, z: -10 }, true)
  }

  return (
    <>
      {refs.current.map((ref, index) => (
        <RigidBody
          key={index + 1}
          ref={refs.current[index + 1]}
          type="dynamic"
          colliders="cuboid"
          onCollisionEnter={null}
          collisionGroups={interactionGroups(2, [0])}
        >
          <mesh
            onClick={() => onHitBox(index + 1)}
            castShadow
            receiveShadow
            geometry={nodes[`Barrel${index + 1}_1`].geometry}
            material={materials['Wood.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes[`Barrel${index + 1}_2`].geometry}
            material={materials['Stone.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes[`Barrel${index + 1}_3`].geometry}
            material={materials['DarkWood.001']}
          />
        </RigidBody>
      ))}
    </>
  )
}

const BoxesDynamic = () => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelOne/LevelOne.glb'
  )

  const arrLength = 10
  const refs = useRef([])

  if (refs.current.length !== arrLength) {
    refs.current = Array(arrLength)
      .fill()
      .map((_, i) => refs.current[i] || createRef())
  }

  const onHitBox = (i) => {
    refs.current[i].current.applyImpulse({ x: 0, y: -100, z: -10 }, true)
  }

  return (
    <>
      {refs.current.map((ref, index) => (
        <RigidBody
          key={index + 1}
          ref={refs.current[index + 1]}
          type="dynamic"
          colliders="cuboid"
          onCollisionEnter={null}
          collisionGroups={interactionGroups(2, [0])}
        >
          <mesh
            onClick={() => onHitBox(index + 1)}
            castShadow
            receiveShadow
            geometry={nodes[`Box${index + 1}_1`].geometry}
            material={materials.DarkWood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes[`Box${index + 1}_2`].geometry}
            material={materials.Wood}
          />
        </RigidBody>
      ))}
    </>
  )
}

const WorldLevelOneDynamic = () => {
  return (
    <>
      <BarrelsDynamic />
      <BoxesDynamic />
    </>
  )
}

const WorldLevelOneTrimesh = () => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelOne/LevelOne.glb'
  )
  return (
    <>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner_1.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner_2.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner001_1.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StairsCorner001_2.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train.geometry}
        material={materials.ColorPalette}
      />
    </>
  )
}

export const WorldLevelOne = (props) => {
  const { nodes, materials } = useGLTF(
    '/assets/models/worldLevelOne/LevelOne.glb'
  )
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cliff.geometry}
        material={materials.Cliff}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Key.geometry}
        material={materials.Golden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large001.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large002.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large003.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large004.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large005.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large006.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large007.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large008.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large009.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large010.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trashcan_Large011.geometry}
        material={materials.LightMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence001.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence002.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence004.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence005.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence008.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence009.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence003.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence006.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence007.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence010.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence011.geometry}
        material={materials.Fence01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ladder.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ladder001.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ladder003.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ladder004.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ladder002.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofMain.geometry}
        material={materials['mat20.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofSide.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RoofSide001.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Train001.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrainRoof.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrainChimney.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrainRoof001.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrainChimney001.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrainChimney2.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrainChimney2001.geometry}
        material={materials.ColorPalette}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint001.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint002.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Checkpoint003.geometry}
        material={materials.Stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft001_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft001_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft002_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft002_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft004_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft004_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft006_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft006_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft007_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft007_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft008_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft008_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft009_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft009_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft010_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft010_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft011_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft011_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft012_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft012_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft013_1.geometry}
        material={materials['dark grey']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BenchLeft013_2.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lock_1.geometry}
        material={materials['mat16.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lock_2.geometry}
        material={materials['mat17.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lock_3.geometry}
        material={materials['mat15.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_1.geometry}
        material={materials['legs.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_2.geometry}
        material={materials.legs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_3.geometry}
        material={materials.floor_is_wet_sign}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_4.geometry}
        material={materials.sign}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_5.geometry}
        material={materials['Material.012']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_6.geometry}
        material={materials['Material.013']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_7.geometry}
        material={materials['floor_is_wet_sign.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_8.geometry}
        material={materials['sign.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco_9.geometry}
        material={materials['Material.014']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_1.geometry}
        material={materials['legs.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_2.geometry}
        material={materials.legs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_3.geometry}
        material={materials.floor_is_wet_sign}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_4.geometry}
        material={materials.sign}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_5.geometry}
        material={materials['Material.012']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_6.geometry}
        material={materials['Material.013']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_7.geometry}
        material={materials['floor_is_wet_sign.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_8.geometry}
        material={materials['sign.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco001_9.geometry}
        material={materials['Material.014']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_1.geometry}
        material={materials['legs.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_2.geometry}
        material={materials.legs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_3.geometry}
        material={materials.floor_is_wet_sign}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_4.geometry}
        material={materials.sign}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_5.geometry}
        material={materials['Material.012']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_6.geometry}
        material={materials['Material.013']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_7.geometry}
        material={materials['floor_is_wet_sign.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_8.geometry}
        material={materials['sign.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Charco002_9.geometry}
        material={materials['Material.014']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_20.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack_21.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack001_1.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack001_2.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_1.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_2.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_3.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_4.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_5.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_6.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_7.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_8.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_9.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_10.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_11.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_12.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_13.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_14.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_15.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_16.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_17.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_18.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_19.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1799109090_20.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_20.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack003_21.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_20.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack004_21.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_20.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack005_21.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_1.geometry}
        material={materials['mat17.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_2.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_3.geometry}
        material={materials['mat19.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_4.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_5.geometry}
        material={materials['mat20.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_6.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_7.geometry}
        material={materials['mat21.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_8.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_9.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_10.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_11.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_12.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_13.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_14.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_15.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_16.geometry}
        material={materials['mat15.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_17.geometry}
        material={materials['mat6.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_18.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_19.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_20.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Backpack006_21.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer006_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer006_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer006_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer002_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer002_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer002_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer003_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer003_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer003_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer004_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer004_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer004_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer007_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer007_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer007_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer001_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer001_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer001_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer005_1.geometry}
        material={materials.Green}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer005_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TrashContainer005_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees001_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees001_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees002_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees002_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees003_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees003_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees004_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees004_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees005_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees005_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees006_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees006_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees007_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees007_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees008_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees008_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees009_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees009_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees010_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees010_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees011_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees011_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees012_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees012_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees013_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees013_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees014_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees014_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees015_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees015_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees016_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees016_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees017_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees017_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees018_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees018_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees019_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees019_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees020_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees020_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees021_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees021_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees022_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees022_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees023_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees023_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees024_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees024_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees025_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees025_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees026_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees026_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees027_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees027_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees028_1.geometry}
        material={materials.look}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trees028_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights004_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights004_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights006_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights006_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights007_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights007_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights008_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights008_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights009_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights009_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights010_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights010_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights011_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights011_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights013_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights013_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights014_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights014_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights015_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights015_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights016_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights016_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights018_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights018_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights019_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights019_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights020_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights020_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights021_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights021_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights022_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights022_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights023_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights023_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights024_1.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights024_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights025.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights025_1.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights026.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights026_1.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights027.geometry}
        material={materials.lamp}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.StreetLights027_1.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared002_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared002_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared003_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared003_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared004_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared004_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared005_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared005_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared006_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared006_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared007_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared007_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared008_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared008_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared009_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared009_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared011_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared011_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared012_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared012_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared013_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared013_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared014_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared014_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared015_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared015_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared017_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared017_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared018_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared018_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared019_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared019_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared020_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared020_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared021_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared021_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared022_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared022_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared023_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared023_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared024_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared024_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared025_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared025_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared026_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared026_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared029_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared029_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared028_1.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared028_2.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared030.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FarolaPared030_1.geometry}
        material={materials.light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCentral_1.geometry}
        material={materials['mat17.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorCentral_2.geometry}
        material={materials['mat22.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch_1.geometry}
        material={materials['Red.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch_2.geometry}
        material={materials['Material.015']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch001_1.geometry}
        material={materials['Red.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch001_2.geometry}
        material={materials['Material.015']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch002_1.geometry}
        material={materials['Red.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch002_2.geometry}
        material={materials['Material.015']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch003_1.geometry}
        material={materials['Red.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arch003_2.geometry}
        material={materials['Material.015']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar001_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar001_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar002_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar002_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar003_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar003_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar004_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar004_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar005_1.geometry}
        material={materials['mat21.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pilar005_2.geometry}
        material={materials['Material.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide_1.geometry}
        material={materials['Red.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide_2.geometry}
        material={materials['Red_Dark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide_3.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide_1.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide_2.geometry}
        material={materials['mat22.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain_1.geometry}
        material={materials['mat19.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain_2.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide004_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide004_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide003_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide003_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide002_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide002_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide001_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide001_2.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide005_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide005_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide006_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide006_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide007_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide007_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide008_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide008_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide009_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide009_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide010_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide010_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide011_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide011_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide012_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide012_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide013_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide013_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide014_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide014_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide015_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide015_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain001_1.geometry}
        material={materials['mat19.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorTrain001_2.geometry}
        material={materials['mat20.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide001_1.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorSide001_2.geometry}
        material={materials['mat22.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide016_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide016_2.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide017_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide017_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide018_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide018_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide019_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide019_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide001_1.geometry}
        material={materials['Red.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide001_2.geometry}
        material={materials['Red_Dark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WallSide001_3.geometry}
        material={materials['mat17.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide020_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide020_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide021_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide021_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide023_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide023_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide024_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide024_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide025_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide025_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide026_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide026_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide027_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide027_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide028_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide028_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide029_1.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide029_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide030.geometry}
        material={materials['mat21.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PilarSide030_1.geometry}
        material={materials['Material.001']}
      />
    </group>
  )
}

useGLTF.preload('/LevelOne.glb')

const WorldLevelOneWithPhysisc = withPhysics(
  WorldLevelOne,
  WorldLevelOneTrimesh,
  WorldLevelOneDynamic
)

export default WorldLevelOneWithPhysisc
